query Trubbel_YetAnotherPrimeReminder {
  currentUser {
    id
    hasPrime
  }
  user {
    self {
      canPrimeSubscribe
      primeSubCreditBenefit {
        renewalDate
        willRenew
      }
    }
  }
}