query Trubbel_ModeratedChannels($after: Cursor, $userID: ID!, $permission: String!) {
	moderatedChannels(first: 100, after: $after) {
		edges {
			cursor
			isLive
			node {
				id
				displayName
				login
        channel {
          hasPermission(userID: $userID, permission: $permission)
        }
				profileImageURL(width: 50)
				broadcastSettings {
					title
					game {
						id
						displayName
						boxArtURL
					}
				}
        chatColor
        primaryColorHex
        lastBroadcast {
          id
          startedAt
        }
				stream {
					createdAt
					viewersCount
				}
        self {
          isEditor
          isFirstTimeChatter
          isFounder
          subscriptionBenefit {
            id
            tier
            purchasedWithPrime
            gift {
              isGift
              giftDate
              gifter {
                id
                login
                displayName
                __typename
              }
              __typename
            }
            __typename
          }
          subscriptionGiftCount
          cumulativeTenure: subscriptionTenure(tenureMethod: CUMULATIVE) {
            months
            __typename
          }
          __typename
        }
			}
		}
		pageInfo {
			hasNextPage
		}
	}
}