query Trubbel_GetVideoInfo($id: ID!) {
	video(id: $id) {
    id
		muteInfo {
      mutedSegmentConnection {
        nodes {
          offset
          duration
        }
      }
    }
		createdAt
	}
}