#import "../fragments/video-info.gql"
#import "../fragments/video-owner.gql"

query Deck_VideoCategory($name: String!, $first: Int, $after: Cursor, $languages: [String!], $types: [BroadcastType!], $sort: VideoSort, $previewWidth: Int, $previewHeight: Int) {
	game(name: $name) {
		id
		displayName
		avatarURL(width: 40, height: 56)
		coverURL(width: 400, height: 60)
		videos(first: $first, after: $after, languages: $languages, types: $types, sort: $sort) {
			pageInfo {
				hasNextPage
			}
			edges {
				cursor
				node {
					...VideoInfo
					...VideoOwner
				}
			}
		}
	}
}