query MassBanTool_GetRecentFollowers( $login: String!, $first: Int!, $after: Cursor ) {
    user( login: $login ) {
        followers( first: $first, after: $after, order: DESC ) {
            edges {
                cursor
                followedAt
                node {
                    displayName
                }
            }
        }
    }
}
