export const FOLLOWING_LIVE_SELECTOR = "[data-a-target=\"following-live-tab\"] [class*=\"ScTitle-sc-\"]";
export const FOLLOWING_VIDEOS_SELECTOR = "[data-a-target=\"following-videos-tab\"] [class*=\"ScTitle-sc-\"]";
export const FOLLOWING_CATEGORIES_SELECTOR = "[data-a-target=\"following-games-tab\"] [class*=\"ScTitle-sc-\"]";
export const FOLLOWING_CHANNELS_SELECTOR = "[data-a-target=\"following-channels-tab\"] [class*=\"ScTitle-sc-\"]";
export const MOST_RECENT_CARD_SELECTOR = ".offline-recommendations-video-card:has([class*=\"offline-recommendations-video-card-border-\"]) :is(.tw-aspect)";
export const MOST_RECENT_SELECTOR = ".offline-recommendations-video-card";
export const TIMESTAMP_SELECTOR = ".timestamp-metadata__bar + p";
export const WHISPER_THREADS_SELECTOR = ".whispers-threads-box__scrollable-area";
export const FOLLOWAGE_USERCARD_SELECTOR = ".user-card strong[title]";
export const POPOUT_CHAT_HEADER_SELECTOR = ".stream-chat-header [data-test-selector=\"chat-room-header-label\"]";
export const MOD_POPOUT_CHAT_HEADER_SELECTOR = ".mod-view-panel-header div h3[title]";
export const DASH_POPOUT_CHAT_HEADER_SELECTOR = ".stream-manager-panel-header div h2[title]";
export const PLAYER_ERROR_OVERLAY_SELECTOR = ".content-overlay-gate";