export const UNICODE_CATEGORIES = {
	'L': 'Letter',
	'Ll': 'Lowercase Letter',
	'Lu': 'Uppercase Letter',
	'Lt': 'Titlecase Letter',
	//'L&': 'Cased Letter',
	'Lm': 'Modifier Letter',
	'Lo': 'Other Letter',

	'M': 'Mark',
	'Mn': 'Non-Spacing Mark',
	'Mc': 'Spacing Combining Mark',
	'Me': 'Enclosing Mark',

	'Z': 'Separator',
	'Zs': 'Space Separator',
	'Zl': 'Line Separator',
	'Zp': 'Paragraph Separator',

	'S': 'Symbol',
	'Sm': 'Math Symbol',
	'Sc': 'Currency Symbol',
	'Sk': 'Modifier Symbol',
	'So': 'Other Symbol',

	'N': 'Number',
	'Nd': 'Decimal Digit Number',
	'Nl': 'Letter Number',
	'No': 'Other Number',

	'P': 'Punctuation',
	'Pd': 'Dash Punctuation',
	'Ps': 'Open Punctuation',
	'Pe': 'Close Punctuation',
	'Pi': 'Initial Punctuation',
	'Pf': 'Final Punctuation',
	'Pc': 'Connector Punctuation',
	'Po': 'Other Punctuation',

	'C': 'Other',
	'Cc': 'Control',
	'Cf': 'Format',
	'Co': 'Private Use',
	'Cs': 'Surrogate',
	'Cn': 'Unassigned'
};

export const UNICODE_SCRIPTS = [
	'Common',
	'Arabic',
	'Armenian',
	'Bengali',
	'Bopomofo',
	'Braille',
	'Buhid',
	'Canadian_Aboriginal',
	'Cherokee',
	'Cyrillic',
	'Devanagari',
	'Ethiopic',
	'Georgian',
	'Greek',
	'Gujarati',
	'Gurmukhi',
	'Han',
	'Hangul',
	'Hanunoo',
	'Hebrew',
	'Hiragana',
	'Inherited',
	'Kannada',
	'Katakana',
	'Khmer',
	'Lao',
	'Latin',
	'Limbu',
	'Malayalam',
	'Mongolian',
	'Myanmar',
	'Ogham',
	'Oriya',
	'Runic',
	'Sinhala',
	'Syriac',
	'Tagalog',
	'Tagbanwa',
	'Tai_Le',
	'Tamil',
	'Telugu',
	'Thaana',
	'Thai',
	'Tibetan',
	'Yi'
];