fragment StreamInfo on Stream {
	id
	type
	viewersCount
	createdAt
	previewImageURL(width: $previewWidth, height: $previewHeight)
	contentClassificationLabels {
		id
		localizedName
	}
	freeformTags {
		id
		name
	}
}