fragment StreamInfo on Stream {
	id
	type
	viewersCount
	createdAt
	previewImageURL(width: $previewWidth, height: $previewHeight)
	tags {
		id
		isAutomated
		isLanguageTag
		localizedName
		tagName
		scope
	}
}